# Generated by Django 4.2.1 on 2023-06-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "name",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "name",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
                ("priority", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "to_do_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todolist.todolist",
                    ),
                ),
            ],
            options={
                "ordering": ["to_do_list", "priority"],
                "unique_together": {("to_do_list", "priority")},
            },
        ),
    ]
